language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - python install_requirements.py dev
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then travis_retry pip install coveralls; fi
script: make check
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coveralls; fi
