language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - python install_requirements.py dev
  - travis_retry pip install coveralls
script: make check
after_success:
  - coveralls
