language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - travis_retry pip install -r dev-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry pip install -r dev-py2-requirements.txt; fi
  - travis_retry pip install coveralls
script: make check
after_success:
  - coveralls
