__title__ = 'Flask-Login'
__description__ = 'User session management for Flask'
__url__ = 'https://github.com/maxcountryman/flask-login'
__version_info__ = ('0', '3', '0')
__version__ = '.'.join(__version_info__)
__author__ = 'Matthew Frazier'
__author_email__ = 'leafstormrush@gmail.com'
__license__ = 'MIT/X11'
__copyright__ = '(c) 2011 by Matthew Frazier'
